#!/usr/bin/env bash
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CONFIG_LOADED=0
if [ -f "$HERE/config.sh" ]; then
  source "$HERE/config.sh"
  CONFIG_LOADED=1
fi

if [ "${1:-}" = "--mark-resolved" ]; then
  if [ $# -lt 2 ]; then
    echo "Usage: $0 --mark-resolved <patch-file>" >&2
    exit 1
  fi
  if [ "$CONFIG_LOADED" -ne 1 ]; then
    echo "config.sh not found at $HERE/config.sh -- needed to know DEST_DIR." >&2
    exit 1
  fi
  PATCH="$2"
  if [ ! -f "$PATCH" ]; then
    echo "Patch file not found: $PATCH" >&2
    exit 1
  fi
  PATCH_HEAD="$(grep -m1 -E '^# patch-head: ' "$PATCH" | sed 's/^# patch-head: //' || true)"
  if [ -z "$PATCH_HEAD" ]; then
    echo "No 'patch-head' header in $PATCH -- this patch predates --since-last-patch support, or wasn't generated by make_patch.sh. Can't mark it resolved." >&2
    exit 1
  fi
  if ! git -C "$DEST_DIR" rev-parse -q --verify "${PATCH_HEAD}^{commit}" >/dev/null 2>&1; then
    echo "patch-head $PATCH_HEAD (from $PATCH) not found in $DEST_DIR -- can't advance 'last-applied'." >&2
    exit 1
  fi
  git -C "$DEST_DIR" tag -f last-applied "$PATCH_HEAD" >/dev/null
  echo "Moved 'last-applied' tag in $DEST_DIR to $PATCH_HEAD."
  exit 0
fi

usage() {
  cat >&2 <<EOF
Usage: $0 [--repo <path>] [<patch-file>] [--since-last-patch]
       $0 <real-repo-path> <patch-file> [--since-last-patch]   (legacy two-arg form)
       $0 --mark-resolved <patch-file>

<patch-file> defaults to $HERE/fix.patch if omitted.
<real-repo-path> defaults to config.sh's SOURCE_DIR if omitted (--repo overrides it).
EOF
  exit 1
}

SINCE_LAST_PATCH=0
REPO_OVERRIDE=""
POSITIONAL=()
while [ $# -gt 0 ]; do
  case "$1" in
    --since-last-patch) SINCE_LAST_PATCH=1; shift ;;
    --repo)
      [ $# -ge 2 ] || usage
      REPO_OVERRIDE="$2"
      shift 2
      ;;
    -*)
      echo "Unknown argument: $1" >&2
      usage
      ;;
    *)
      POSITIONAL+=("$1")
      shift
      ;;
  esac
done

case "${#POSITIONAL[@]}" in
  0)
    PATCH="$HERE/fix.patch"
    ;;
  1)
    PATCH="${POSITIONAL[0]}"
    ;;
  2)
    # Legacy form: <real-repo-path> <patch-file>
    if [ -n "$REPO_OVERRIDE" ]; then
      echo "Can't combine --repo with the legacy two-argument form." >&2
      usage
    fi
    REPO_OVERRIDE="${POSITIONAL[0]}"
    PATCH="${POSITIONAL[1]}"
    ;;
  *)
    usage
    ;;
esac

if [ -n "$REPO_OVERRIDE" ]; then
  REPO="$REPO_OVERRIDE"
elif [ "$CONFIG_LOADED" -eq 1 ] && [ -n "${SOURCE_DIR:-}" ]; then
  REPO="$SOURCE_DIR"
else
  echo "No repo path given: pass --repo <path> (or the legacy first argument), or set SOURCE_DIR in config.sh." >&2
  usage
fi

if [ "$SINCE_LAST_PATCH" -eq 1 ] && [ "$CONFIG_LOADED" -ne 1 ]; then
  echo "config.sh not found at $HERE/config.sh -- needed for --since-last-patch (DEST_DIR)." >&2
  exit 1
fi

if [ ! -d "$REPO/.git" ]; then
  echo "Not a git repo: $REPO" >&2
  exit 1
fi
if [ ! -f "$PATCH" ]; then
  echo "Patch file not found: $PATCH" >&2
  exit 1
fi

# Resolve to absolute paths before cd'ing into REPO, or a relative $PATCH
# (the common case) silently breaks once the cwd changes.
REPO="$(cd "$REPO" && pwd)"
PATCH="$(cd "$(dirname "$PATCH")" && pwd)/$(basename "$PATCH")"

if [ "$CONFIG_LOADED" -eq 1 ] && [ -n "${DEST_DIR:-}" ] && [ -d "$DEST_DIR/.git" ]; then
  echo "--- checking patch freshness against $DEST_DIR's current HEAD ---"
  PATCH_HEAD="$(grep -m1 -E '^# patch-head: ' "$PATCH" | sed 's/^# patch-head: //' || true)"
  DEST_HEAD="$(git -C "$DEST_DIR" rev-parse HEAD)"
  if [ -z "$PATCH_HEAD" ]; then
    echo "No 'patch-head' header in $PATCH (older patch, or make_patch.sh couldn't determine it) -- skipping freshness check."
  elif [ "$PATCH_HEAD" = "$DEST_HEAD" ]; then
    echo "OK: $PATCH was generated from $DEST_DIR's current HEAD ($DEST_HEAD)."
  else
    echo "ERROR: $PATCH was generated from $PATCH_HEAD, but $DEST_DIR's HEAD is now $DEST_HEAD." >&2
    echo "The sanitized repo has moved on since this patch was made -- re-run make_patch.sh and use the new fix.patch." >&2
    exit 1
  fi
  echo
fi

cd "$REPO"

if [ -n "$(git status --porcelain)" ]; then
  echo "Warning: working tree at $REPO is not clean. Commit or stash before applying." >&2
fi

echo "--- checking if the source-commit recorded in the sanitized baseline matches HEAD ---"
SOURCE_COMMIT="$(grep -m1 -E '^# source-commit: ' "$PATCH" | sed 's/^# source-commit: //' || true)"
HEAD_HASH="$(git log -1 --format=%H HEAD)"

if [ -z "$SOURCE_COMMIT" ]; then
  echo "No 'source-commit' header found in $PATCH (older patch, or make_patch.sh couldn't determine it) -- skipping check."
elif ! git rev-parse --verify -q "${SOURCE_COMMIT}^{commit}" >/dev/null 2>&1; then
  echo "WARNING: source-commit $SOURCE_COMMIT recorded in the patch is not present in this repo's history at all -- cannot verify it's an ancestor of HEAD ($HEAD_HASH). Review carefully before applying."
elif git merge-base --is-ancestor "$SOURCE_COMMIT" HEAD; then
  echo "OK: source-commit $SOURCE_COMMIT is an ancestor of HEAD ($HEAD_HASH)."
else
  echo "WARNING: source-commit $SOURCE_COMMIT recorded in the sanitized baseline is NOT an ancestor of HEAD ($HEAD_HASH)."
  echo "The real repo may have moved on since the sanitized snapshot was taken -- review the patch carefully before applying."
fi
echo

if [ "$SINCE_LAST_PATCH" -eq 1 ]; then
  echo "--- applying with 3-way merge (--since-last-patch) ---"
  APPLY_OK=1
  git apply -3 "$PATCH" || APPLY_OK=0

  if [ "$APPLY_OK" -eq 1 ]; then
    echo "Applied cleanly (3-way). Review with 'git diff', then commit."
    PATCH_HEAD="$(grep -m1 -E '^# patch-head: ' "$PATCH" | sed 's/^# patch-head: //' || true)"
    if [ -n "$PATCH_HEAD" ] && git -C "$DEST_DIR" rev-parse -q --verify "${PATCH_HEAD}^{commit}" >/dev/null 2>&1; then
      git -C "$DEST_DIR" tag -f last-applied "$PATCH_HEAD" >/dev/null
      echo "Advanced 'last-applied' tag in $DEST_DIR to $PATCH_HEAD."
    else
      echo "WARNING: no usable 'patch-head' header in $PATCH -- 'last-applied' tag NOT advanced." >&2
      echo "Re-tag manually in $DEST_DIR, or use --mark-resolved with a patch that has the header." >&2
    fi
    exit 0
  fi

  CONFLICT_FILES=$(git diff --name-only --diff-filter=U)
  if [ -z "$CONFLICT_FILES" ]; then
    echo "git apply -3 failed and left no merge-conflict state -- nothing was applied. Inspect the error above." >&2
    exit 1
  fi

  echo
  echo "3-way merge left conflicts (do not commit yet) in:"
  echo "$CONFLICT_FILES"
  echo
  echo "Resolve the conflict markers by hand, 'git add' the resolved files, then commit in $REPO."
  echo "'last-applied' tag in $DEST_DIR was NOT advanced."
  echo "Once resolved and committed, run: $0 --mark-resolved $PATCH"
  exit 1
fi

if git apply --check "$PATCH" 2>/dev/null; then
  git apply "$PATCH"
  echo "Applied cleanly. Review with 'git diff', then commit."
  exit 0
fi

echo "Clean apply failed (likely a hunk touching a line adjacent to a redacted secret)."
echo "Falling back to 'git apply --reject': applying what matches, leaving .rej files for the rest."
git apply --reject "$PATCH" || true

REJ_FILES=$(find . -name "*.rej" -not -path "./.git/*")
if [ -n "$REJ_FILES" ]; then
  echo
  echo "Unresolved hunks (fix by hand, then delete the .rej files):"
  echo "$REJ_FILES"
else
  echo "No .rej files left -- everything applied."
fi
